### ISSUE TITLE
Formatting often fails

### ISSUE THREAD

**Issue by sporto** [elm-tooling/elm-language-client-vscode#18]
When I save a file if formats sometimes, most of the time it fails.

I see the following in the output:

```
[2019-08-02 08:56:04.847] [renderer1] [warning] Aborted format on save after 750ms
[2019-08-02 08:56:34.569] [renderer1] [warning] Aborted format on save after 750ms
[2019-08-02 08:56:36.458] [renderer1] [warning] Aborted format on save after 750ms
[2019-08-02 08:56:47.032] [renderer1] [warning] Aborted format on save after 750ms
```

## Expected Behavior

Always format

## Current Behavior

Aborts formatting

## Steps to Reproduce (for bugs)

Save file

## Your Environment

* Version used: 0.4.2
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.36.1
* Environment name and version (e.g. node.js 5.4): 10.16.0
* Operating System and version: PopOS.

**Comment by Razzeee** [comment]
Please see https://github.com/elm-tooling/elm-language-server/issues/85

Or better https://github.com/avh4/binwrap/issues/31

Basically try to not install `elm-format` via npm. Or hope for the new version to improve runtime, not sure when it will be released.

**Comment by sporto** [comment]
Ok, not sure if it makes any difference, but I'm downloaded the linux binary, not the npm version

**Comment by Razzeee** [comment]
And you only have that on your PC? Without config the extension will just use `elm-format` from path.

It would be news to me, that that version can also be slow. But then again, it probably just takes a very very big file to achieve that :)

Maybe you can run and share commands similar to https://github.com/avh4/binwrap/issues/31#issuecomment-508502196

**Comment by sporto** [comment]
Hmm, we also have `elm-format` in our `package.json` because I `elm-graphql` needs that. this extension might be trying to use that, let me see.

**Comment by sporto** [comment]
Ok, not that, is just slow with the binary too

**Comment by andys8** [comment]
What are the times for `time elm-format --version` on your path and maybe with `time ./node_modules/.bin/elm-format --version` for comparison?

**Comment by andys8** [comment]
The timeout can be raised in vs code. This could be a workaround, but I'd prefer if we find ways to speed things up.

`"editor.formatOnSaveTimeout"`

https://code.visualstudio.com/updates/v1_22#_configurable-format-on-save-timeout

**Comment by andys8** [comment]
@Razzeee The vscode plugin (without lsp) recommends setting the value, too. https://github.com/Krzysztof-Cieslak/vscode-elm/blob/a66cc0acb70e5c7d4755b72c3ccaf6d528388690/README.md#formatting-with-elm-format

**Comment by Razzeee** [comment]
We could add this to the readme or a FAQ. But I would like for it to be faster :)

**Comment by sporto** [comment]
```
➜ time elm-format src/Elm/App.elm --yes
Processing file src/Elm/App.elm
0.21user 0.00system 0:00.24elapsed 92%CPU

➜ time ./node_modules/.bin/elm-format src/Elm/App.elm --yes
Processing file src/Elm/App.elm
0.58user 0.03system 0:00.60elapsed 103%CPU
```

**Comment by sporto** [comment]
I raised the timeout to 5000, still doesn't work. So for me this is something else.

**Comment by Razzeee** [comment]
Anything else in the log that's suspicious?

**Comment by sporto** [comment]
This is what I see in the output with `elmLS/client` in the dropdown

```
[Info  - 1:00:51 pm] Formatting was requested
[Info  - 1:00:51 pm] Diagnostics were requested due to a file open or save
[Info  - 1:00:52 pm] Connection to server got closed. Server will restart.
[Error - 1:00:52 pm] Request textDocument/formatting failed.
Error: Connection got disposed.
	at Object.dispose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:962:16)
	at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Error - 1:00:52 pm] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:962:16)
	at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Error - 1:00:52 pm] Request codeLens/resolve failed.
Error: Connection got disposed.
	at Object.dispose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:962:16)
	at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
	at Socket.emit (events.js:182:13)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Info  - 1:00:52 pm] Activating tree-sitter...
[Info  - 1:00:52 pm] Starting language server for folder: file:///home/sebastian/Source/staxio/stax
```

**Comment by sporto** [comment]
Sorry, I have deleted my last comment. That only happens if `elmLS.elmFormatPath` is blank.
If this is `elm-format` then that error doesn't show. It just fails.

**Comment by sporto** [comment]
It looks like if the extension is busy receiving other things e.g. elm-analyse results then it fails to format.

I can replicate succesful formating by

- Waiting for the extension to be idle (see nothing in the output for a few seconds)
- Save
- See format happening

And failing by:

- Seeing a message like `Received new elm-analyse`
- Not waiting and hitting save
- Then format fails

**Comment by andys8** [comment]
@sporto Is there a difference in behavior in the first 10 seconds (when `elm-analyse` is executed initially) and afterwards?

I noticed some interference between those two, too. But there could be more differences depending on the client implementation (because I'm using vim/coc).

https://github.com/elm-tooling/elm-language-server/issues/125

**Comment by sporto** [comment]
@andys8 when I first open VS Code, I see a message like:

```
[Info  - 9:12:50 am] initializing - folder: "file:///home/sebastian/Source/..."
```

Then after 40 seconds

```
[Info  - 9:13:28 am] Done parsing all files.
```

For all this time, elm-format doesn't work. Then after that elm-format finally formats.

After that. If I make a change and save, elm-format works inmmediatelly. But if I make another rapid change it doesn't. I have to wait about 10-12 seconds for it to work again.

So initially I have to wait much longer.

**Comment by andys8** [comment]
Oah, 40 seconds. How large is the code base and the number of dependencies?

**Comment by sporto** [comment]
- 96k lines of Elm 
- 53 deps (direct and indirect)

**Comment by andys8** [comment]
Thanks. Is it possible to share the `elm.json` as an example, to have a look if the amount of dependencies is causing the slowdown?

**Comment by sporto** [comment]
Sure elm.json:

```
{
    "type": "application",
    "source-directories": [
        "src/Elm"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "NoRedInk/elm-json-decode-pipeline": "1.0.0",
            "NoRedInk/elm-simple-fuzzy": "1.0.3",
            "avh4/elm-color": "1.0.0",
            "dillonkearns/elm-graphql": "4.3.1",
            "elm/browser": "1.0.1",
            "elm/core": "1.0.2",
            "elm/html": "1.0.0",
            "elm/http": "2.0.0",
            "elm/json": "1.1.3",
            "elm/regex": "1.0.0",
            "elm/svg": "1.0.1",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm-community/dict-extra": "2.4.0",
            "elm-community/json-extra": "4.0.0",
            "elm-community/list-extra": "8.2.2",
            "elm-community/maybe-extra": "5.0.0",
            "elm-community/result-extra": "2.2.1",
            "elm-explorations/markdown": "1.0.0",
            "ggb/numeral-elm": "1.4.3",
            "jinjor/elm-debounce": "3.0.0",
            "jschomay/elm-paginate": "3.1.1",
            "json-tools/json-schema": "1.0.2",
            "json-tools/json-value": "1.0.1",
            "justinmimbs/date": "3.1.2",
            "justinmimbs/time-extra": "1.1.0",
            "krisajenkins/remotedata": "6.0.1",
            "larribas/elm-multi-input": "2.0.0",
            "linuss/smooth-scroll": "1.1.0",
            "mgold/elm-nonempty-list": "4.0.2",
            "noahzgordon/elm-color-extra": "1.0.2",
            "rtfeldman/elm-css": "16.0.1",
            "rtfeldman/elm-iso8601-date-strings": "1.1.3",
            "sporto/elm-select": "3.1.2",
            "sporto/polylinear-scale": "1.0.2",
            "sporto/qs": "1.0.1",
            "sporto/time-distance": "1.0.1",
            "stoeffel/elm-verify": "5.0.0",
            "supermario/elm-countries": "1.0.3",
            "zwilias/elm-html-string": "2.0.2"
        },
        "indirect": {
            "NoRedInk/elm-string-conversions": "1.0.1",
            "Skinney/murmur3": "2.0.8",
            "elm/bytes": "1.0.7",
            "elm/file": "1.0.1",
            "elm/parser": "1.1.0",
            "elm/random": "1.0.0",
            "elm/virtual-dom": "1.0.2",
            "elm-community/easing-functions": "2.0.0",
            "fredcy/elm-parseint": "2.0.1",
            "jschomay/elm-bounded-number": "2.1.0",
            "lukewestby/elm-string-interpolate": "1.0.3",
            "rtfeldman/elm-hex": "1.0.0",
            "zwilias/elm-utf-tools": "2.0.1"
        }
    },
    "test-dependencies": {
        "direct": {
            "elm-explorations/test": "1.2.2"
        },
        "indirect": {
            "tripokey/elm-fuzzy": "5.2.1"
        }
    }
}
```

**Comment by Razzeee** [comment]
This feels more like three issues:

1. Initial parsing takes long
2. elm-format does not work while initializing
3. elm-format stagnates after multiple rapid uses

I'll move this into the language server repo for now. We should probably have an issue for each of these.
