### ISSUE TITLE
Language server unable to start - Unkown system error

### ISSUE THREAD

**Issue by abury** [elm-tooling/elm-language-client-vscode#197]
Hey all

I've been trying to get the elm language client to work for a few days without much luck. It looks like the language server is unable to start due to an unkown system error. It cites being unable to determine the elm version, but I'm not sure why that would be the case. Elm is installed globally and locally within node_modules.

Would love any insights on how I can get this to work!

I've double and triple checked everything. Elm is installed correctly, node 14 is installed, everything else elm related is working fine.

## Current Behavior
Language server fails to start, output below:
```bash
[Info  - 8:55:47 am] Loading Elm tree-sitter syntax from ../../../../.vscode/extensions/elmtooling.elm-ls-vscode-2.2.0/server/out/tree-sitter-elm.wasm
[Info  - 8:55:47 am] Found 2 elm.json files for workspace /Users/<username>/Documents/apps/<project-name>/client
[Info  - 8:55:47 am] Found 1 unique elmWorkspaces for workspace /Users/<username>/Documents/apps/<project-name>/client
[Info  - 8:55:47 am] Starting language server for folder: file:///Users/<username>/Documents/apps/<project-name>/client
[Warn  - 8:55:47 am] {"errno":-8,"code":"Unknown system error -8","syscall":"spawnSync elm","path":"elm","spawnargs":["--version"],"originalMessage":"spawnSync elm Unknown system error -8","shortMessage":"Command failed with Unknown system error -8: elm --version\nspawnSync elm Unknown system error -8","command":"elm --version","stdout":"","stderr":"","failed":true,"timedOut":false,"isCanceled":false,"killed":false}
[Warn  - 8:55:47 am] Could not figure out elm version, this will impact how good the server works. 
 Error: Command failed with Unknown system error -8: elm --version
spawnSync elm Unknown system error -8
    at Object.spawnSync (internal/child_process.js:1067:20)
    at Object.spawnSync (child_process.js:611:24)
    at Function.module.exports.sync (/Users/<username>/.vscode/extensions/elmtooling.elm-ls-vscode-2.2.0/server/node_modules/execa/index.js:167:25)
    at execCmdSync (/Users/<username>/.vscode/extensions/elmtooling.elm-ls-vscode-2.2.0/server/out/compiler/utils/elmUtils.js:45:32)
    at Object.getElmVersion (/Users/<username>/.vscode/extensions/elmtooling.elm-ls-vscode-2.2.0/server/out/compiler/utils/elmUtils.js:90:20)
    at Program.<anonymous> (/Users/<username>/.vscode/extensions/elmtooling.elm-ls-vscode-2.2.0/server/out/compiler/program.js:172:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/<username>/.vscode/extensions/elmtooling.elm-ls-vscode-2.2.0/server/out/compiler/program.js:24:58)
[Info  - 8:55:47 am] Reading elm.json from /Users/<username>/Documents/apps/<project-name>/client/elm.json
[Warn  - 8:55:47 am] {"errno":-8,"code":"Unknown system error -8","syscall":"spawnSync elm","path":"elm","spawnargs":["make"],"originalMessage":"spawnSync elm Unknown system error -8","shortMessage":"Command failed with Unknown system error -8: elm make\nspawnSync elm Unknown system error -8","command":"elm make","stdout":"","stderr":"","failed":true,"timedOut":false,"isCanceled":false,"killed":false}
[Error - 8:55:47 am] Error parsing files for /Users/<username>/Documents/apps/<project-name>/client/elm.json:
Error: ENOENT: no such file or directory, open '/Users/<username>/.elm/undefined/packages/NoRedInk/elm-json-decode-pipeline/1.0.0/elm.json'
[Error - 8:55:47 am] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'getTree' of undefined
[Error - 8:55:47 am] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'getTree' of undefined
[Error - 8:55:47 am] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'getTree' of undefined
  Code: -32603 
[Error - 8:55:48 am] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'getTree' of undefined
  Code: -32603 
[Error - 8:55:48 am] TypeError: Cannot read property 'getTree' of undefined delayed processing of request
[Error - 8:55:48 am] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed with message: Cannot read property 'getTree' of undefined
  Code: -32603 
[Error - 8:55:50 am] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'getTree' of undefined
  Code: -32603 
[Error - 8:55:50 am] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'getTree' of undefined
  Code: -32603 
```

## Your Environment

* Version used: 2.2.0
* Editor name and version VSCode 1.57.1
* Environment name and version node v14.16.1, elm 0.19.1
* Operating System and version: OSX 10.15.7

**Comment by abury** [comment]
I was able to resolve the issue by manually setting the global path(s) in the extension settings, but would be interested to know what stopped it from picking up the global/local versions manually.

**Comment by Razzeee** [comment]
what's happening, when you call `elm` in the folder of you project via a shell of your choice?

**Comment by abury** [comment]
@Razzeee looks good:

```bash
Hi, thank you for trying out Elm 0.19.1. I hope you like it!
.... etc
Be sure to ask on the Elm slack if you run into trouble! Folks are friendly and
happy to help out. They hang out there because it is fun, so be kind to get the
best results!

```

**Comment by Razzeee** [comment]
Not sure then, we're using https://github.com/sindresorhus/execa to find where your executable lives, maybe you can try a minimal typescript project, that just uses this to call elm. If that works, something else is going on.
