### ISSUE TITLE
[error] Error: The language client requires VS Code version ^1.42.0 but received version 1.41.1

### ISSUE THREAD

**Issue by JwanKhalaf** [elm-tooling/elm-language-client-vscode#83]
Hello

I am on Manjaro Linux and I am doing some Elm development. Everything used to work fine, but recently the tooling is broken.

`elm-format` no longer works and I can't do things like `Go To Definition`

![image](https://user-images.githubusercontent.com/42877376/75102059-e288be80-55dc-11ea-8e09-f6874432c106.png)

The error in text is:

```
"_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-02-23 01:00:14.514] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/merge-conflict/dist/extension
[2020-02-23 01:00:14.519] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-02-23 01:00:14.519] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/search-result/dist/extension.js
[2020-02-23 01:00:14.521] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":true,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"*"}
[2020-02-23 01:00:14.521] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/jwan/.vscode-oss/extensions/esbenp.prettier-vscode-3.20.0/dist/extension
[2020-02-23 01:00:14.561] [exthost] [info] ExtensionService#_doActivateExtension ritwickdey.LiveServer {"startup":true,"extensionId":{"value":"ritwickdey.LiveServer","_lower":"ritwickdey.liveserver"},"activationEvent":"*"}
[2020-02-23 01:00:14.561] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/jwan/.vscode-oss/extensions/ritwickdey.liveserver-5.6.1/out/src/extension
[2020-02-23 01:00:14.745] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":true,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"workspaceContains:package.json"}
[2020-02-23 01:00:14.745] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/npm/dist/main
[2020-02-23 01:00:14.798] [exthost] [error] Activating extension elmTooling.elm-ls-vscode failed due to an error:
[2020-02-23 01:00:14.799] [exthost] [error] Error: The language client requires VS Code version ^1.42.0 but received version 1.41.1
	at LanguageClient.checkVersion (/home/jwan/.vscode-oss/extensions/elmtooling.elm-ls-vscode-0.9.1/client/node_modules/vscode-languageclient/lib/main.js:123:19)
	at new LanguageClient (/home/jwan/.vscode-oss/extensions/elmtooling.elm-ls-vscode-0.9.1/client/node_modules/vscode-languageclient/lib/main.js:104:18)
	at didOpenTextDocument (/home/jwan/.vscode-oss/extensions/elmtooling.elm-ls-vscode-0.9.1/client/out/extension.js:111:32)
	at Array.forEach (<anonymous>)
	at /home/jwan/.vscode-oss/extensions/elmtooling.elm-ls-vscode-0.9.1/client/out/extension.js:117:42
	at Generator.next (<anonymous>)
	at /home/jwan/.vscode-oss/extensions/elmtooling.elm-ls-vscode-0.9.1/client/out/extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/home/jwan/.vscode-oss/extensions/elmtooling.elm-ls-vscode-0.9.1/client/out/extension.js:4:12)
	at activate (/home/jwan/.vscode-oss/extensions/elmtooling.elm-ls-vscode-0.9.1/client/out/extension.js:51:12)
	at Function._callActivateOptional (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:911)
	at Function._callActivate (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:562)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:694:651
	at async Promise.all (index 0)
[2020-02-23 01:00:14.943] [exthost] [info] eager extensions activated
[2020-02-23 01:18:48.397] [exthost] [info] ExtensionService#_doActivateExtension vscode.css-language-features {"startup":false,"extensionId":{"value":"vscode.css-language-features","_lower":"vscode.css-language-features"},"activationEvent":"onLanguage:scss"}
[2020-02-23 01:18:48.397] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/css-language-features/client/dist/cssMain
```

**Comment by Razzeee** [comment]
I'm actually on manjaro too and developed this version on 1.41.x so it's very surprising to me.

However, I've bumped the minimal vscode version for this and will be releasing that shortly.

The real question now is, if I need to unpublish the last two versions, for you to drop down to 0.8.0 correctly.

**Comment by Razzeee** [comment]
Seems like arch released a new version?
https://www.archlinux.org/packages/community/x86_64/code/

Good to close?

**Comment by dstpierre** [comment]
I'm on Arch, just updated to 1.42 and this is the error I'm getting:

```
[2020-02-27 10:28:11.746] [exthost] [error] Activating extension elmTooling.elm-ls-vscode failed due to an error:
[2020-02-27 10:28:11.747] [exthost] [error] Error: Cannot find module 'request'
Require stack:
- /home/dstpierre/.vscode-oss/extensions/elmtooling.elm-ls-vscode-0.9.3/client/out/elmPackage.js
- /home/dstpierre/.vscode-oss/extensions/elmtooling.elm-ls-vscode-0.9.3/client/out/extension.js
- /usr/lib/code/out/vs/loader.js
```

**Comment by Razzeee** [comment]
Can you deinstall and install the extension in vscode? I have had an report from an user which sounded similar. Not sure how it can fail on installing.

**Comment by dstpierre** [comment]
Very strange, I've removed and reinstalled multiple time yesterday.

Seems to be working now, thanks.
